CFLAGS = -Wall -Wextra -Werror
AR = ar rc
NAME = ./libft.a
SRCDIR = ./srcs
OBJSDIR = ./objs
SRCS = $(addprefix $(SRCDIR)/,$(FILES)) 
OBJS = $(addprefix $(OBJSDIR)/,$(notdir $(SRCS:.c=.o)))
INCLUDES = -I ./includes
FILES = \
	ft_atoi.c ft_bzero.c ft_calloc.c ft_isalnum.c ft_isalpha.c\
	ft_isascii.c ft_isdigit.c ft_isprint.c ft_isspace.c ft_itoa.c\
	ft_memchr.c ft_memcmp.c ft_memcpy.c ft_memmove.c ft_memset.c\
	ft_putchar_fd.c ft_putendl_fd.c ft_putnbr_fd.c ft_putstr_fd.c ft_split.c\
	ft_strchr.c ft_strdup.c ft_striteri.c ft_strjoin.c ft_strlcat.c\
	ft_strlcpy.c ft_strlen.c ft_strmapi.c ft_strncmp.c ft_strnstr.c\
	ft_strrchr.c ft_strtrim.c ft_substr.c ft_tolower.c ft_toupper.c\
	get_next_line.c\
	ft_lstadd_back.c ft_lstadd_front.c ft_lstclear.c ft_lstdelone.c ft_lstiter.c\
	ft_lstlast.c ft_lstnew.c ft_lstsize.c ft_lstmap.c

# DEBUG = -g -fsanitize=address
DEBUG = -g

$(OBJSDIR)/%.o : $(SRCDIR)/%.c
	@$(CC) $(CFLAGS) $(INCLUDES) $(DEBUG) -c $< -o $@

$(NAME): $(OBJS)
	@$(AR) $@ $^

all: $(NAME)
	@echo "libft all"

clean:
	@$(RM) $(OBJS) 

fclean: clean
	@$(RM) $(NAME)

re: fclean all

.PHONY : all clean fclean re bonus

echo :
	@echo $(INCLUDES)
	@echo $(SRCS)
	@echo $(OBJS)
	@echo 